import { computed } from "vue";
import { useI18n } from "vue-i18n";
import type { Course } from "~/types/courseTypes";

const messages = {
  de: {
    back: "Zur Übersicht",
    course: "Dein Lernweg",
    start: "Loslegen",
    continue: "Weiterlernen",
    revisit: "Noch einmal ansehen",
    open: "Kurs öffnen",
    contents: "Dein Weg durch den Kurs",
    goals: "Das lernst du",
    requirements: "Das brauchst du schon",
    about: "Über diesen Kurs",
    lessons: "Lerneinheiten",
    completed: "erledigt",
    complete: "Als erledigt markieren",
    done: "Erledigt",
    next: "Weiter",
    previous: "Zurück",
    practice: "Jetzt ausprobieren",
    practiceOpen: "Übung öffnen",
    practiceMore: "Weitere Übungen",
    practiceEmpty: "Hier gibt es gerade keine weiteren Übungen.",
    practiceError: "Die Übungen konnten nicht geladen werden. Versuch es noch einmal.",
    retry: "Noch einmal versuchen",
    loading: "Einen Moment …",
    loadError: "Der Kurs konnte nicht geladen werden.",
    saveError: "Dein Fortschritt konnte nicht gespeichert werden. Versuch es noch einmal.",
    materials: "Videos und weitere Inhalte",
    section: "Abschnitt",
    lesson: "Einheit",
    learning: "Lernen",
    topicIntro: "Such dir ein Lernziel aus. Im Kurs geht es Schritt für Schritt weiter.",
    topicEmpty: "Für dieses Thema bereiten wir gerade Inhalte vor.",
    topicCourses: "Dein nächster Schritt",
    browsePractice: "Übungen zum Thema",
    progress: "Dein Fortschritt",
    step: "Schritt",
    of: "von",
    video: "Video ansehen",
    noLesson: "In diesem Kurs sind noch keine Lerneinheiten verfügbar.",
    finish: "Zur Kursübersicht",
    end: "Du bist am Ende dieses Abschnitts angekommen.",
    courseAccess: "Kurs freischalten",
    available: "Bereit",
    prerequisite: "Erst die Grundlagen davor abschließen",
    introduction: "Kennengelernt",
    solved: "Selbst gelöst",
    preview: "Das erwartet dich",
    free: "Kostenlos",
    errorTitle: "Das hat gerade nicht geklappt",
    saved: "Gespeichert",
  },
  en: {
    back: "Back to overview",
    course: "Your learning path",
    start: "Get started",
    continue: "Keep learning",
    revisit: "Take another look",
    open: "Open course",
    contents: "Your way through the course",
    goals: "What you'll learn",
    requirements: "What you'll need",
    about: "About this course",
    lessons: "learning units",
    completed: "completed",
    complete: "Mark as completed",
    done: "Completed",
    next: "Continue",
    previous: "Back",
    practice: "Give it a try",
    practiceOpen: "Open exercise",
    practiceMore: "More exercises",
    practiceEmpty: "There are no more exercises here right now.",
    practiceError: "We couldn't load the exercises. Please try again.",
    retry: "Try again",
    loading: "Just a moment …",
    loadError: "We couldn't load this course.",
    saveError: "We couldn't save your progress. Please try again.",
    materials: "Videos and more",
    section: "Section",
    lesson: "Unit",
    learning: "Learn",
    topicIntro: "Choose what you'd like to learn. Your course takes you through it step by step.",
    topicEmpty: "We're preparing learning materials for this topic.",
    topicCourses: "Your next step",
    browsePractice: "Practice this topic",
    progress: "Your progress",
    step: "Step",
    of: "of",
    video: "Watch video",
    noLesson: "This course doesn't have any learning units yet.",
    finish: "Back to the course",
    end: "You've reached the end of this section.",
    courseAccess: "Unlock course",
    available: "Ready",
    prerequisite: "Complete the earlier foundations first",
    introduction: "Introduced",
    solved: "Solved by you",
    preview: "What's ahead",
    free: "Free",
    errorTitle: "Something went wrong",
    saved: "Saved",
  },
};

export function useCourseExperienceCopy() {
  const { locale } = useI18n();
  const language = computed(() => (locale.value.startsWith("de") ? "de" : "en"));
  return {
    copy: computed(() => messages[language.value]),
    localizeCourse: (course: Course): Course => {
      const text = course.translations?.[language.value];
      if (!text) return course;
      return {
        ...course,
        title: text.title ?? course.title,
        description: text.description ?? course.description,
        learning_goals: text.learning_goals ?? course.learning_goals,
        requirements: text.requirements ?? course.requirements,
      };
    },
    localized: (value?: { de?: string; en?: string } | string | null) =>
      typeof value === "string" ? value : value?.[language.value] || value?.en || "",
  };
}
