export const itLabCopy = (locale: string) =>
  locale.startsWith("de")
    ? {
        experiment: "Ausprobieren",
        observation: "Darauf kannst du achten",
        check: "Antworten prüfen",
        finish: "Weiter",
        reset: "Übungsstand zurücksetzen",
        retry: "Vergleiche deine Antwort noch einmal mit dem Versuch.",
        correct: "Das passt zu deinem Versuch.",
        choose: "Bitte auswählen",
        limit:
          "Der Übungsstand lässt sich gerade nicht weiter bearbeiten. Du kannst ihn zurücksetzen und erneut ausprobieren.",
        invalid:
          "Dieser Übungsstand konnte nicht gelesen werden. Setze ihn zurück, um neu anzufangen.",
        unavailable: "Dieser Lernraum ist gerade nicht verfügbar.",
        tryFirst: "Probier zuerst etwas in der Arbeitsfläche aus.",
        input: "Eingabe",
        text: "Text",
        value: "Zahlenwert",
        rule: "Regel",
        step: "Ein Schritt",
        run: "Ausführen",
        restart: "Ablauf von vorn",
        output: "Ausgabe",
        working: "Arbeitswerte im vereinfachten Modell",
        current: "Ausgeführter Schritt",
        ready: "Noch kein Schritt ausgeführt",
        emptyOutput: "Noch keine Ausgabe",
        cpu: "CPU führt die Anweisung aus; Arbeitswerte sind hier vereinfacht dargestellt, keine CPU-Registeransicht.",
        read: "Eingabe lesen",
        double: "Wert verdoppeln",
        add: "3 addieren",
        emit: "Ausgeben",
        initialise: "Summe und Anzahl auf 0 setzen",
        readItem: "Nächsten Eintrag lesen",
        resetSum: "Summe auf 0 zurücksetzen",
        accumulate: "Passenden Eintrag zur Summe hinzufügen",
        gte1: "Wert mindestens 1?",
        gt1: "Wert größer als 1?",
        present: "vorhanden",
        empty: "leer",
        sum: "Summe",
        count: "Berücksichtigte Einträge",
        swap: "Mit dem nächsten Schritt tauschen",
        inclusive: "Bedingung",
        gte: "mindestens 1 (>=)",
        gt: "größer als 1 (>)",
        resetPosition: "Summe innerhalb der Wiederholung zurücksetzen",
        yes: "Ja",
        no: "Nein",
        dataset: "Testdaten",
        sumData: "2, 3, 1",
        projectData: "2, 3, 0",
        boundary: "Grenzfall: 1",
        emptyData: "Leere Liste",
        preview: "Berechnete Seitenvorschau",
        projectTitle: "Treffpunkt",
        projectOrigin:
          "Vorbereiteter Projektstand: gerettete Text-, Daten- und Symboldateien. Eigene frühere Änderungen werden hier nicht automatisch übernommen.",
        bit: "Bit",
        weight: "Gewicht",
        states: "Mögliche Zustände",
        maximum: "Größter Wert",
        bytes: "UTF-8-Bytes (dezimal)",
        decoder: "Bytes lesen als",
        utf8: "UTF-8",
        latin: "ISO-8859-1",
        decoded: "Dargestellter Text",
        byteCount: "Bytes",
        pixel: "Pixel",
        row: "Zeile",
        column: "Spalte",
        colour: "Farbe",
        palette: "Palette",
        twoColours: "2 Farben · 1 Bit pro Pixel",
        fourColours: "4 Farben · 2 Bit pro Pixel",
        paint: "Ausgewählten Pixel setzen",
        payload: "Rohe Pixeldaten, ohne Dateikopf, Palette oder Kompression",
        paletteLoss:
          "Dein Bild nutzt Farben 2 oder 3. Ordne diese ausdrücklich neu zu, bevor du die Palette verkleinerst.",
        remap: "Farben 2 und 3 durch Farbe 1 ersetzen",
        black: "Schwarz",
        white: "Weiß",
        blue: "Blau",
        orange: "Orange",
        files: "Gespeicherte Dateien",
        file: "Datei",
        noFiles: "Keine Datei auf diesem Übungsmedium",
        savedData: "Gespeicherter Inhalt",
        open: "In neuer Editorinstanz öffnen",
        edit: "Entwurf im Arbeitsspeicher",
        save: "Datei speichern",
        power: "Stromausfall simulieren",
        copy: "Kopie im Archiv anlegen",
        rename: "Endung zu .png ändern",
        viewImage: "Als Bild öffnen",
        backup: "Gespeicherte Dateien sichern",
        delete: "Ausgewählte Datei löschen",
        restore: "Sicherung in neuen Ordner wiederherstellen",
        saveCopy: "Entwurf als eigene Kopie sichern",
        backupChoice: "Sicherungsstand prüfen",
        old: "Älterer Stand ohne Symbol",
        complete: "Vollständiger Stand",
        backupFiles: "Dateien auf getrenntem Sicherungsmedium",
        noBackup: "Es gibt noch keine Sicherung.",
        syncDelete: "Vergleich: Löschung auch in Spiegel übernehmen",
        process: "Laufende Instanz",
        close: "Ausgewählte Instanz beenden",
        job: "Rechenarbeit starten",
        jobLabel: "Rechenarbeit",
        noProcess: "Kein Editor geöffnet. Wähle eine gespeicherte Datei und öffne sie.",
        ram: "RAM-Plätze",
        cpuSteps: "Belegte CPU-Schritte je Runde",
        storage: "Gespeicherte Nutzdaten in Bytes",
        resourcesNote:
          "Modellwerte: 8 RAM-Plätze, 4 CPU-Schritte pro Runde. Kein Maß für die Leistung deines Geräts.",
        exists: "Die Zieldatei ist schon da. Ihr Inhalt bleibt erhalten.",
        storageFull: "Auf dem Übungsmedium passt keine weitere Datei hinein.",
        copied: "Die unabhängige Kopie ist gespeichert. Öffne sie, um sie zu bearbeiten.",
        opened: "Eine neue Editorinstanz hat den gespeicherten Inhalt geladen.",
        ramFull:
          "Die neue Instanz passt nicht mehr in den Modell-RAM. Beende eine andere Instanz und vergleiche.",
        missingFile: "Die ursprüngliche Datei fehlt. Der offene Entwurf ist noch da.",
        readOnly:
          "Die Datei ist schreibgeschützt. Du kannst deinen Entwurf als eigene Kopie sichern.",
        saved: "Der Entwurf ist jetzt in der Datei gespeichert.",
        powerLoss: "Die flüchtigen Entwürfe sind weg. Öffne die gespeicherte Datei erneut.",
        closed: "Diese Instanz ist beendet. Die Programmdatei bleibt vorhanden.",
        jobStarted: "Die Rechenarbeit belegt die vier CPU-Schritte dieser Modellrunde.",
        renamed:
          "Nur die Endung hat sich geändert. Die Daten haben noch ihr ursprüngliches Format.",
        imageOpened: "Die Daten enthalten ein Pixelbild.",
        wrongFormat:
          "Diese Daten sind Text, kein Pixelbild. Die Endung allein wandelt sie nicht um.",
        backupMade:
          "Der gespeicherte Stand liegt auf dem getrennten Sicherungsmedium. Ungespeicherte Entwürfe sind nicht enthalten.",
        deleted: "Die Datei ist gelöscht. Eine vorhandene getrennte Sicherung bleibt erhalten.",
        restored:
          "Die Sicherung wurde in einen neuen Ordner kopiert. Öffne die Dateien und prüfe ihren Inhalt.",
        syncedDeletion:
          "Dieser reine Spiegel hat die Löschung übernommen. Hier ist keine Wiederherstellungsversion enthalten.",
        programKept:
          "Das Editorprogramm bleibt auf dem dauerhaften Speicher, auch wenn keine Instanz läuft.",
        local: "Lokale Verbindung",
        uplink: "Verbindung nach draußen",
        route: "Route zum entfernten Server",
        dns: "Passender DNS-Eintrag",
        tls: "Zertifikat passt zum Host",
        access: "Server erlaubt den Seitenzugriff",
        image: "Bildpfad zeigt auf vorhandenes Symbol",
        on: "Vorhanden",
        off: "Unterbrochen / fehlt",
        target: "Ziel",
        printer: "Lokaler Drucker",
        server: "Entfernter Server",
        test: "Verbindung prüfen",
        request: "Seite anfordern",
        path: "Angefragter Pfad",
        host: "Host: infoseite.example",
        url: "Modelladresse",
        routeDescription:
          "Laptop → lokales Netz → Router → Server (192.0.2.20). Der Drucker (192.0.2.10) bleibt im lokalen Netz.",
        report: "Letzter Prüfbericht",
        stale: "Du hast den Aufbau verändert. Prüfe erneut, um den aktuellen Stand zu sehen.",
        noTest: "Noch kein Test ausgeführt",
        localDown: "Lokale Verbindung fehlt. Der nächste Weg kann noch nicht geprüft werden.",
        localOk: "Lokales Netz erreichbar",
        printerOk: "Lokaler Drucker erreichbar",
        dnsFailed: "Name nicht gefunden. Noch keine Verbindung und keine HTTP-Antwort.",
        dnsOk: "Host aufgelöst: infoseite.example → 192.0.2.20",
        routeFailed: "Weg zum entfernten Server unterbrochen",
        routeOk: "Entfernten Server über den Router erreicht",
        tlsFailed: "Zertifikat passt nicht zum Host. Keine HTTP-Anfrage gesendet.",
        tlsOk:
          "Geschützter Kanal zum passenden Host aufgebaut; dies prüft nicht den Wahrheitsgehalt des Inhalts.",
        http403: "HTTP 403: Der Server verweigert diese Anfrage.",
        http404: "HTTP 404: Für diesen Seitenpfad wird keine Ressource geliefert.",
        html200: "HTML: HTTP 200, Seitendaten empfangen",
        image200: "Bild: HTTP 200, Symboldaten empfangen",
        image404: "Bild: HTTP 404, Symbol fehlt; die Textseite ist trotzdem angekommen.",
        page: "Darstellung am zweiten Gerät",
        missingImage: "Symbol konnte nicht geladen werden",
        trustNote:
          "Eine geschützte Verbindung bestätigt keine Behauptung auf der Seite und verleiht keine Zugriffsrechte.",
        delivered: "Ankunftsfolge der Abschnitte",
        deliver: "Abschnitt senden",
        retryTransfer: "Fehlenden Abschnitt erneut senden",
        clearTransfer: "Übertragung neu beginnen",
        receive: "Nach Byteposition zusammengesetzte Daten",
        transferNote:
          "Abschnitt DEF fehlt im ersten Lauf. Sende GHI und ABC in beliebiger Reihenfolge, dann DEF erneut. Das Modell zeigt einen zuverlässigen Bytestrom, keine festen TCP-Nachrichtengrenzen.",
        incomplete: "Noch unvollständig",
      }
    : {
        experiment: "Explore",
        observation: "What to look for",
        check: "Check answers",
        finish: "Continue",
        reset: "Reset this exercise",
        retry: "Compare your answer with the experiment again.",
        correct: "That matches the experiment.",
        choose: "Choose an option",
        limit:
          "This exercise state cannot accept another edit right now. You can reset it and try again.",
        invalid: "This exercise state could not be read. Reset it to start again.",
        unavailable: "This learning room is currently unavailable.",
        tryFirst: "Try something in the workspace first.",
        input: "Input",
        text: "Text",
        value: "Numeric value",
        rule: "Rule",
        step: "One step",
        run: "Run",
        restart: "Restart the procedure",
        output: "Output",
        working: "Working values in the simplified model",
        current: "Executed instruction",
        ready: "No instruction executed yet",
        emptyOutput: "No output yet",
        cpu: "The CPU executes the instruction; working values are simplified here, not a CPU register view.",
        read: "Read input",
        double: "Double the value",
        add: "Add 3",
        emit: "Output",
        initialise: "Set total and count to 0",
        readItem: "Read the next item",
        resetSum: "Reset total to 0",
        accumulate: "Add an eligible item to the total",
        gte1: "Value at least 1?",
        gt1: "Value greater than 1?",
        present: "present",
        empty: "empty",
        sum: "Total",
        count: "Included items",
        swap: "Swap with the next instruction",
        inclusive: "Condition",
        gte: "at least 1 (>=)",
        gt: "greater than 1 (>)",
        resetPosition: "Reset total inside the repetition",
        yes: "Yes",
        no: "No",
        dataset: "Test data",
        sumData: "2, 3, 1",
        projectData: "2, 3, 0",
        boundary: "Boundary: 1",
        emptyData: "Empty list",
        preview: "Computed page preview",
        projectTitle: "Treffpunkt",
        projectOrigin:
          "Prepared project state: recovered text, data and icon files. Your earlier personal edits are not automatically carried over here.",
        bit: "Bit",
        weight: "Weight",
        states: "Possible states",
        maximum: "Greatest value",
        bytes: "UTF-8 bytes (decimal)",
        decoder: "Interpret bytes as",
        utf8: "UTF-8",
        latin: "ISO-8859-1",
        decoded: "Displayed text",
        byteCount: "Bytes",
        pixel: "Pixel",
        row: "Row",
        column: "Column",
        colour: "Colour",
        palette: "Palette",
        twoColours: "2 colours · 1 bit per pixel",
        fourColours: "4 colours · 2 bits per pixel",
        paint: "Set selected pixel",
        payload: "Raw pixel data, without header, palette or compression",
        paletteLoss:
          "Your picture uses colours 2 or 3. Explicitly remap these before reducing the palette.",
        remap: "Replace colours 2 and 3 with colour 1",
        black: "Black",
        white: "White",
        blue: "Blue",
        orange: "Orange",
        files: "Saved files",
        file: "File",
        noFiles: "No file on this exercise medium",
        savedData: "Saved contents",
        open: "Open in a new editor instance",
        edit: "Draft in working memory",
        save: "Save file",
        power: "Simulate power loss",
        copy: "Create an archive copy",
        rename: "Change extension to .png",
        viewImage: "Open as an image",
        backup: "Back up saved files",
        delete: "Delete selected file",
        restore: "Restore backup into a new folder",
        saveCopy: "Save draft as your own copy",
        backupChoice: "Inspect backup",
        old: "Older snapshot without icon",
        complete: "Complete snapshot",
        backupFiles: "Files on the separate backup medium",
        noBackup: "There is no backup yet.",
        syncDelete: "Compare: propagate deletion to mirror",
        process: "Running instance",
        close: "Stop selected instance",
        job: "Start compute work",
        jobLabel: "Compute work",
        noProcess: "No editor is open. Select a saved file and open it.",
        ram: "RAM slots",
        cpuSteps: "Occupied CPU steps per round",
        storage: "Saved payload in bytes",
        resourcesNote:
          "Model values: 8 RAM slots, 4 CPU steps per round. These do not measure your device's performance.",
        exists: "The destination file already exists. Its contents are preserved.",
        storageFull: "No more files fit on this exercise medium.",
        copied: "The independent copy is saved. Open it to edit it.",
        opened: "A new editor instance loaded the saved contents.",
        ramFull: "The new instance does not fit in model RAM. Stop another instance and compare.",
        missingFile: "The original file is missing. The open draft still exists.",
        readOnly: "The file is read-only. You can save the draft as your own copy.",
        saved: "The draft is now saved in the file.",
        powerLoss: "Volatile drafts are gone. Open the saved file again.",
        closed: "This instance has stopped. The program file still exists.",
        jobStarted: "Compute work occupies all four CPU steps in this model round.",
        renamed: "Only the extension changed. The data still has its original format.",
        imageOpened: "The data contains a pixel image.",
        wrongFormat:
          "This data is text, not a pixel image. Changing the extension does not convert it.",
        backupMade:
          "The saved state is on the separate backup medium. Unsaved drafts are not included.",
        deleted: "The file is deleted. An existing separate backup is preserved.",
        restored:
          "The backup was copied into a new folder. Open the files and check their contents.",
        syncedDeletion:
          "This simple mirror propagated the deletion. It contains no recovery version.",
        programKept:
          "The editor program remains in persistent storage even when no instance is running.",
        local: "Local connection",
        uplink: "Upstream connection",
        route: "Route to remote server",
        dns: "Correct DNS entry",
        tls: "Certificate matches the host",
        access: "Server allows page access",
        image: "Image path points to an existing icon",
        on: "Available",
        off: "Disconnected / missing",
        target: "Target",
        printer: "Local printer",
        server: "Remote server",
        test: "Test connection",
        request: "Request page",
        path: "Requested path",
        host: "Host: infoseite.example",
        url: "Model address",
        routeDescription:
          "Laptop → local network → router → server (192.0.2.20). The printer (192.0.2.10) stays on the local network.",
        report: "Latest test report",
        stale: "You changed the setup. Test again to see its current state.",
        noTest: "No test performed yet",
        localDown: "Local connection is missing. The next part cannot be checked yet.",
        localOk: "Local network reachable",
        printerOk: "Local printer reachable",
        dnsFailed: "Name not found. No connection or HTTP response yet.",
        dnsOk: "Host resolved: infoseite.example → 192.0.2.20",
        routeFailed: "Route to the remote server is interrupted",
        routeOk: "Remote server reached through the router",
        tlsFailed: "Certificate does not match the host. No HTTP request sent.",
        tlsOk:
          "Protected channel to the matching host established; this does not verify the truth of the content.",
        http403: "HTTP 403: The server refuses this request.",
        http404: "HTTP 404: No resource is provided for this page path.",
        html200: "HTML: HTTP 200, page data received",
        image200: "Image: HTTP 200, icon data received",
        image404: "Image: HTTP 404, icon missing; the text page still arrived.",
        page: "Display on the second device",
        missingImage: "The icon could not be loaded",
        trustNote: "A protected connection does not verify a page's claims or grant access rights.",
        delivered: "Chunk arrival order",
        deliver: "Send chunk",
        retryTransfer: "Resend missing chunk",
        clearTransfer: "Restart transfer",
        receive: "Data assembled by byte position",
        transferNote:
          "Chunk DEF is missing in the first run. Send GHI and ABC in any order, then resend DEF. The model shows a reliable byte stream, not fixed TCP message boundaries.",
        incomplete: "Not complete yet",
      };
